import {test} from 'node:test';import assert from 'node:assert/strict';import {makeHandler} from '../netlify/lib/core.mjs';
const seed=[{id:'robotics',title:'Robotics',provider:'Provider',years:'Y2–Y3',season:'Season 2',school:'Lower School',day:'Monday',active:true}];
function setup(){const map=new Map();const store={list:async({prefix})=>({blobs:[...map.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))}),get:async k=>structuredClone(map.get(k)??null),setJSON:async(k,v)=>map.set(k,structuredClone(v))};const env={STAFF_ACCESS_CODE:'test-staff-code',ADMIN_ACCESS_CODE:'test-admin-code',SESSION_SECRET:'a'.repeat(48)};const handler=makeHandler({store,env,seed});const request=(action,body,cookie='',origin='https://qa.example')=>handler(new Request('https://qa.example/.netlify/functions/api?action='+action,{method:body?'POST':'GET',headers:{origin,cookie,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}));const login=async code=>{const r=await request('login',{code});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0]};return{request,login,map,env}}
const review={sessions:'1',activityId:'robotics',reviewer:'Test reviewer',date:'2026-10-02',score:4,checklist:Array(10).fill('yes'),priority:'Follow-up',review:'Clear routines and engaged pupils.',nextSteps:'Prepare a challenge task.',due:'2026-10-09',owner:'CCA team'};
test('anonymous access and incorrect codes are rejected',async()=>{const s=setup();assert.equal((await s.request('data')).status,401);assert.equal((await s.request('login',{code:'wrong'})).status,401)});
test('staff can submit and shared admin reads preserved snapshot',async()=>{const s=setup(),staff=await s.login(s.env.STAFF_ACCESS_CODE),admin=await s.login(s.env.ADMIN_ACCESS_CODE);assert.equal((await s.request('review',review,staff)).status,201);const data=await(await s.request('data',undefined,admin)).json();assert.equal(data.reviews.length,1);assert.equal(data.reviews[0].activitySnapshot.title,'Robotics');assert.equal((await(await s.request('data',undefined,staff)).json()).reviews.length,0)});
test('staff cannot change activities or action status',async()=>{const s=setup(),staff=await s.login(s.env.STAFF_ACCESS_CODE);assert.equal((await s.request('activity',seed[0],staff)).status,403);assert.equal((await s.request('status',{id:'a',status:'Closed'},staff)).status,403)});
test('admin edits and archive suppresses new observations',async()=>{const s=setup(),admin=await s.login(s.env.ADMIN_ACCESS_CODE);assert.equal((await s.request('activity',{...seed[0],active:false},admin)).status,200);assert.equal((await s.request('review',review,admin)).status,400)});
test('invalid scores, checklist, next steps and missing name are rejected',async()=>{const s=setup(),staff=await s.login(s.env.STAFF_ACCESS_CODE);for(const change of [{score:6},{score:2.5},{checklist:[]},{nextSteps:''},{reviewer:''}])assert.equal((await s.request('review',{...review,...change},staff)).status,400)});
test('concurrent observations remain separate records',async()=>{const s=setup(),staff=await s.login(s.env.STAFF_ACCESS_CODE);const responses=await Promise.all(Array.from({length:12},()=>s.request('review',review,staff)));assert.ok(responses.every(r=>r.status===201));assert.equal([...s.map.keys()].filter(k=>k.startsWith('review/')).length,12)});
test('cross-origin writes and tampered sessions are rejected',async()=>{const s=setup(),staff=await s.login(s.env.STAFF_ACCESS_CODE);assert.equal((await s.request('review',review,staff,'https://other.example')).status,403);assert.equal((await s.request('data',undefined,staff+'tampered')).status,401)});
test('admin tracks action and access-code rotation invalidates session',async()=>{const s=setup(),admin=await s.login(s.env.ADMIN_ACCESS_CODE);const r=await(await s.request('review',review,admin)).json();assert.equal((await s.request('status',{id:r.review.id,status:'Closed'},admin)).status,200);assert.equal(s.map.get('review/'+r.review.id).status,'Closed');s.env.ADMIN_ACCESS_CODE='new-admin-code';assert.equal((await s.request('data',undefined,admin)).status,401)});
test('unconfigured setup fails closed',async()=>{const s=setup();delete s.env.SESSION_SECRET;assert.equal((await s.request('data')).status,503)});
test('selected login area rejects the other role code',async()=>{const s=setup();assert.equal((await s.request('login',{code:s.env.ADMIN_ACCESS_CODE,role:'staff'})).status,401);assert.equal((await s.request('login',{code:s.env.STAFF_ACCESS_CODE,role:'admin'})).status,401)});
test('only admin imports activities; repeat uploads update without duplicates',async()=>{const s=setup(),staff=await s.login(s.env.STAFF_ACCESS_CODE),admin=await s.login(s.env.ADMIN_ACCESS_CODE),a={...seed[0],title:'New club',room:'Room A'};assert.equal((await s.request('import',{activities:[a]},staff)).status,403);assert.equal((await s.request('import',{activities:[a]},admin)).status,200);assert.equal((await s.request('import',{activities:[{...a,room:'Room B'}]},admin)).status,200);const data=await(await s.request('data',undefined,staff)).json();assert.equal(data.activities.filter(x=>x.title==='New club').length,1);assert.equal(data.activities.find(x=>x.title==='New club').room,'Room B');assert.equal((await s.request('review',{...review,activityId:data.activities.find(x=>x.title==='New club').id},staff)).status,201)});
test('invalid import rows are rejected before any writes',async()=>{const s=setup(),admin=await s.login(s.env.ADMIN_ACCESS_CODE);assert.equal((await s.request('import',{activities:[seed[0],{...seed[0],title:''}]},admin)).status,400);assert.equal(s.map.size,0)});

test('sessions observed accepts 1–10 and rejects missing or out-of-range counts',async()=>{const s=setup(),staff=await s.login(s.env.STAFF_ACCESS_CODE);for(const sessions of ['', '0','11','1.5','one'])assert.equal((await s.request('review',{...review,sessions},staff)).status,400);for(const sessions of ['1','10'])assert.equal((await s.request('review',{...review,sessions},staff)).status,201)});
